Add theme gruvbox.
PrismLauncher/Themes pull request #51
Opened 2024-06-14 09:40 UTC by SophrTemin

2024-06-14 09:41 UTC, FarParticul reviewed
review

2024-07-08 23:24 UTC, TheKodeToad requested changes
Sorry for the long waiting time! I was going to review but I got distracted.

2024-07-08 23:24 UTC, TheKodeToad commented on themes/Gruvbox/Readme.md
> +![Grvbx Preview](preview.png)
```suggestion
![Gruvbox Preview](preview.png)
```

2024-07-08 23:24 UTC, TheKodeToad commented on themes/Gruvbox/resources/.keep
it's a bit excessive to add a license to an empty file

2024-07-09 04:48 UTC, SophrTemin commented on themes/Gruvbox/resources/.keep
If you need to remove it, I'll remove it, after all I copied from others)

2024-07-09 04:51 UTC, SophrTemin commented
I'll probably write here, but it turned out that when I posted the icons I did not upload the catalog with them and it turned out that I lost them (request with icons but without icons turns out).

2024-07-09 05:01 UTC, SophrTemin commented
can I change the sdpx names to sophrtemin now? I just happened to have changed my nickname all this time

2024-07-10 11:43 UTC, TheKodeToad commented on themes/Gruvbox/resources/.keep
It's not in other themes, I don't think

2024-07-10 17:51 UTC, SophrTemin commented on themes/Gruvbox/resources/.keep
> It's not in other themes, I don't think

I thought it was, I will remove it in another request and close this one (there is already a theme and icons).

2024-07-10 17:53 UTC, closed without merging